version: '3.4'

services:
  application:
    image: ${DOCKER_REGISTRY-}application
    build:
      context: .
      dockerfile: Api/Dockerfile
  applicationDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: applicationDb
    environment:
        - SA_PASSWORD=RaynorRaiders44
        - ACCEPT_EULA=Y
    ports:
        - "1441:1433"